//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 80 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: 5482 Adobe Falls Rd #15 San Diego, California (CA), 92120
      ///
      /// Key: 5482 Adobe Falls Rd #15 San Diego, California (CA), 92120
      ///
      /// Locales: en
      var adobeFallsRd15SanDiegoCaliforniaCA92120: RswiftResources.StringResource { .init(key: "5482 Adobe Falls Rd #15\nSan Diego, California (CA), 92120", tableName: "Localizable", source: source, developmentValue: "5482 Adobe Falls Rd #15\nSan Diego, California (CA), 92120", comment: nil) }

      /// en translation: Activities
      ///
      /// Key: Activities
      ///
      /// Locales: en
      var activities: RswiftResources.StringResource { .init(key: "Activities", tableName: "Localizable", source: source, developmentValue: "Activities", comment: nil) }

      /// en translation: Address
      ///
      /// Key: Address
      ///
      /// Locales: en
      var address: RswiftResources.StringResource { .init(key: "Address", tableName: "Localizable", source: source, developmentValue: "Address", comment: nil) }

      /// en translation: All Products
      ///
      /// Key: All Products
      ///
      /// Locales: en
      var allProducts: RswiftResources.StringResource { .init(key: "All Products", tableName: "Localizable", source: source, developmentValue: "All Products", comment: nil) }

      /// en translation: Already Have an Account
      ///
      /// Key: Already Have an Account
      ///
      /// Locales: en
      var alreadyHaveAnAccount: RswiftResources.StringResource { .init(key: "Already Have an Account", tableName: "Localizable", source: source, developmentValue: "Already Have an Account", comment: nil) }

      /// en translation: Apply Filter
      ///
      /// Key: Apply Filter
      ///
      /// Locales: en
      var applyFilter: RswiftResources.StringResource { .init(key: "Apply Filter", tableName: "Localizable", source: source, developmentValue: "Apply Filter", comment: nil) }

      /// en translation: Best Sellers
      ///
      /// Key: Best Sellers
      ///
      /// Locales: en
      var bestSellers: RswiftResources.StringResource { .init(key: "Best Sellers", tableName: "Localizable", source: source, developmentValue: "Best Sellers", comment: nil) }

      /// en translation: Change password
      ///
      /// Key: Change password
      ///
      /// Locales: en
      var changePassword: RswiftResources.StringResource { .init(key: "Change password", tableName: "Localizable", source: source, developmentValue: "Change password", comment: nil) }

      /// en translation: Checkout Now
      ///
      /// Key: Checkout Now
      ///
      /// Locales: en
      var checkoutNow: RswiftResources.StringResource { .init(key: "Checkout Now", tableName: "Localizable", source: source, developmentValue: "Checkout Now", comment: nil) }

      /// en translation: Choose your location
      ///
      /// Key: Choose your location
      ///
      /// Locales: en
      var chooseYourLocation: RswiftResources.StringResource { .init(key: "Choose your location", tableName: "Localizable", source: source, developmentValue: "Choose your location", comment: nil) }

      /// en translation: Clear All
      ///
      /// Key: Clear All
      ///
      /// Locales: en
      var clearAll: RswiftResources.StringResource { .init(key: "Clear All", tableName: "Localizable", source: source, developmentValue: "Clear All", comment: nil) }

      /// en translation: Color
      ///
      /// Key: Color
      ///
      /// Locales: en
      var color: RswiftResources.StringResource { .init(key: "Color", tableName: "Localizable", source: source, developmentValue: "Color", comment: nil) }

      /// en translation: Color: %@
      ///
      /// Key: ColorFormat
      ///
      /// Locales: en
      var colorFormat: RswiftResources.StringResource1<String> { .init(key: "ColorFormat", tableName: "Localizable", source: source, developmentValue: "Color: %@", comment: nil) }

      /// en translation: Confirm
      ///
      /// Key: Confirm
      ///
      /// Locales: en
      var confirm: RswiftResources.StringResource { .init(key: "Confirm", tableName: "Localizable", source: source, developmentValue: "Confirm", comment: nil) }

      /// en translation: Confirm Payment
      ///
      /// Key: Confirm Payment
      ///
      /// Locales: en
      var confirmPayment: RswiftResources.StringResource { .init(key: "Confirm Payment", tableName: "Localizable", source: source, developmentValue: "Confirm Payment", comment: nil) }

      /// en translation: Confirm password
      ///
      /// Key: Confirm password
      ///
      /// Locales: en
      var confirmPassword: RswiftResources.StringResource { .init(key: "Confirm password", tableName: "Localizable", source: source, developmentValue: "Confirm password", comment: nil) }

      /// en translation: Congratulation! Your account already created. Please login to get amazing experience!
      ///
      /// Key: Congratulation! Your account already created. Please login to get amazing experience!
      ///
      /// Locales: en
      var congratulationYourAccountAlreadyCreatedPleaseLoginToGetAmazingExperience: RswiftResources.StringResource { .init(key: "Congratulation! Your account already created.\nPlease login to get amazing experience!", tableName: "Localizable", source: source, developmentValue: "Congratulation! Your account already created.\nPlease login to get amazing experience!", comment: nil) }

      /// en translation: Create Account
      ///
      /// Key: Create Account
      ///
      /// Locales: en
      var createAccount: RswiftResources.StringResource { .init(key: "Create Account", tableName: "Localizable", source: source, developmentValue: "Create Account", comment: nil) }

      /// en translation: Create new password
      ///
      /// Key: Create new password
      ///
      /// Locales: en
      var createNewPassword: RswiftResources.StringResource { .init(key: "Create new password", tableName: "Localizable", source: source, developmentValue: "Create new password", comment: nil) }

      /// en translation: Create your password
      ///
      /// Key: Create your password
      ///
      /// Locales: en
      var createYourPassword: RswiftResources.StringResource { .init(key: "Create your password", tableName: "Localizable", source: source, developmentValue: "Create your password", comment: nil) }

      /// en translation: Create your username
      ///
      /// Key: Create your username
      ///
      /// Locales: en
      var createYourUsername: RswiftResources.StringResource { .init(key: "Create your username", tableName: "Localizable", source: source, developmentValue: "Create your username", comment: nil) }

      /// en translation: Didn't receive the code? 
      ///
      /// Key: Didn’t receive the code? 
      ///
      /// Locales: en
      var didnTReceiveTheCode: RswiftResources.StringResource { .init(key: "Didn’t receive the code? ", tableName: "Localizable", source: source, developmentValue: "Didn't receive the code? ", comment: nil) }

      /// en translation: Edit
      ///
      /// Key: Edit
      ///
      /// Locales: en
      var edit: RswiftResources.StringResource { .init(key: "Edit", tableName: "Localizable", source: source, developmentValue: "Edit", comment: nil) }

      /// en translation: Email
      ///
      /// Key: Email
      ///
      /// Locales: en
      var email: RswiftResources.StringResource { .init(key: "Email", tableName: "Localizable", source: source, developmentValue: "Email", comment: nil) }

      /// en translation: Enter your email
      ///
      /// Key: Enter your email
      ///
      /// Locales: en
      var enterYourEmail: RswiftResources.StringResource { .init(key: "Enter your email", tableName: "Localizable", source: source, developmentValue: "Enter your email", comment: nil) }

      /// en translation: Enter your new password
      ///
      /// Key: Enter your new password
      ///
      /// Locales: en
      var enterYourNewPassword: RswiftResources.StringResource { .init(key: "Enter your new password", tableName: "Localizable", source: source, developmentValue: "Enter your new password", comment: nil) }

      /// en translation: Enter your password
      ///
      /// Key: Enter your password
      ///
      /// Locales: en
      var enterYourPassword: RswiftResources.StringResource { .init(key: "Enter your password", tableName: "Localizable", source: source, developmentValue: "Enter your password", comment: nil) }

      /// en translation: Enter your promo code
      ///
      /// Key: Enter your promo code
      ///
      /// Locales: en
      var enterYourPromoCode: RswiftResources.StringResource { .init(key: "Enter your promo code", tableName: "Localizable", source: source, developmentValue: "Enter your promo code", comment: nil) }

      /// en translation: Filter By
      ///
      /// Key: Filter By
      ///
      /// Locales: en
      var filterBy: RswiftResources.StringResource { .init(key: "Filter By", tableName: "Localizable", source: source, developmentValue: "Filter By", comment: nil) }

      /// en translation: Follow
      ///
      /// Key: Follow
      ///
      /// Locales: en
      var follow: RswiftResources.StringResource { .init(key: "Follow", tableName: "Localizable", source: source, developmentValue: "Follow", comment: nil) }

      /// en translation: Forgot Password?
      ///
      /// Key: Forgot Password?
      ///
      /// Locales: en
      var forgotPassword: RswiftResources.StringResource { .init(key: "Forgot Password?", tableName: "Localizable", source: source, developmentValue: "Forgot Password?", comment: nil) }

      /// en translation: Go to Homepage
      ///
      /// Key: Go to Homepage
      ///
      /// Locales: en
      var goToHomepage: RswiftResources.StringResource { .init(key: "Go to Homepage", tableName: "Localizable", source: source, developmentValue: "Go to Homepage", comment: nil) }

      /// en translation: House
      ///
      /// Key: House
      ///
      /// Locales: en
      var house: RswiftResources.StringResource { .init(key: "House", tableName: "Localizable", source: source, developmentValue: "House", comment: nil) }

      /// en translation: Info Missing
      ///
      /// Key: Info Missing
      ///
      /// Locales: en
      var infoMissing: RswiftResources.StringResource { .init(key: "Info Missing", tableName: "Localizable", source: source, developmentValue: "Info Missing", comment: nil) }

      /// en translation: Last Search
      ///
      /// Key: Last Search
      ///
      /// Locales: en
      var lastSearch: RswiftResources.StringResource { .init(key: "Last Search", tableName: "Localizable", source: source, developmentValue: "Last Search", comment: nil) }

      /// en translation: Let’s find your unforgettable event. Choose a location below to get started.
      ///
      /// Key: Let’s find your unforgettable event. Choose a location below to get started.
      ///
      /// Locales: en
      var letSFindYourUnforgettableEventChooseALocationBelowToGetStarted: RswiftResources.StringResource { .init(key: "Let’s find your unforgettable event. Choose a location below to get started.", tableName: "Localizable", source: source, developmentValue: "Let’s find your unforgettable event. Choose a location below to get started.", comment: nil) }

      /// en translation: Location
      ///
      /// Key: Location
      ///
      /// Locales: en
      var location: RswiftResources.StringResource { .init(key: "Location", tableName: "Localizable", source: source, developmentValue: "Location", comment: nil) }

      /// en translation: Login Account
      ///
      /// Key: Login Account
      ///
      /// Locales: en
      var loginAccount: RswiftResources.StringResource { .init(key: "Login Account", tableName: "Localizable", source: source, developmentValue: "Login Account", comment: nil) }

      /// en translation: Mainpage
      ///
      /// Key: Mainpage
      ///
      /// Locales: en
      var mainpage: RswiftResources.StringResource { .init(key: "Mainpage", tableName: "Localizable", source: source, developmentValue: "Mainpage", comment: nil) }

      /// en translation: Message
      ///
      /// Key: Message
      ///
      /// Locales: en
      var message: RswiftResources.StringResource { .init(key: "Message", tableName: "Localizable", source: source, developmentValue: "Message", comment: nil) }

      /// en translation: Messages
      ///
      /// Key: Messages
      ///
      /// Locales: en
      var messages: RswiftResources.StringResource { .init(key: "Messages", tableName: "Localizable", source: source, developmentValue: "Messages", comment: nil) }

      /// en translation: My Cart
      ///
      /// Key: My Cart
      ///
      /// Locales: en
      var myCart: RswiftResources.StringResource { .init(key: "My Cart", tableName: "Localizable", source: source, developmentValue: "My Cart", comment: nil) }

      /// en translation: My Order
      ///
      /// Key: My Order
      ///
      /// Locales: en
      var myOrder: RswiftResources.StringResource { .init(key: "My Order", tableName: "Localizable", source: source, developmentValue: "My Order", comment: nil) }

      /// en translation: OK
      ///
      /// Key: OK
      ///
      /// Locales: en
      var oK: RswiftResources.StringResource { .init(key: "OK", tableName: "Localizable", source: source, developmentValue: "OK", comment: nil) }

      /// en translation: Or using other method
      ///
      /// Key: Or using other method
      ///
      /// Locales: en
      var orUsingOtherMethod: RswiftResources.StringResource { .init(key: "Or using other method", tableName: "Localizable", source: source, developmentValue: "Or using other method", comment: nil) }

      /// en translation: Order Successfully
      ///
      /// Key: Order Successfully
      ///
      /// Locales: en
      var orderSuccessfully: RswiftResources.StringResource { .init(key: "Order Successfully", tableName: "Localizable", source: source, developmentValue: "Order Successfully", comment: nil) }

      /// en translation: Order Tracking
      ///
      /// Key: Order Tracking
      ///
      /// Locales: en
      var orderTracking: RswiftResources.StringResource { .init(key: "Order Tracking", tableName: "Localizable", source: source, developmentValue: "Order Tracking", comment: nil) }

      /// en translation: Password
      ///
      /// Key: Password
      ///
      /// Locales: en
      var password: RswiftResources.StringResource { .init(key: "Password", tableName: "Localizable", source: source, developmentValue: "Password", comment: nil) }

      /// en translation: Payment
      ///
      /// Key: Payment
      ///
      /// Locales: en
      var payment: RswiftResources.StringResource { .init(key: "Payment", tableName: "Localizable", source: source, developmentValue: "Payment", comment: nil) }

      /// en translation: Payment Method
      ///
      /// Key: Payment Method
      ///
      /// Locales: en
      var paymentMethod: RswiftResources.StringResource { .init(key: "Payment Method", tableName: "Localizable", source: source, developmentValue: "Payment Method", comment: nil) }

      /// en translation: Please login with registered account
      ///
      /// Key: Please login with registered account
      ///
      /// Locales: en
      var pleaseLoginWithRegisteredAccount: RswiftResources.StringResource { .init(key: "Please login with registered account", tableName: "Localizable", source: source, developmentValue: "Please login with registered account", comment: nil) }

      /// en translation: Popular Products
      ///
      /// Key: Popular Products
      ///
      /// Locales: en
      var popularProducts: RswiftResources.StringResource { .init(key: "Popular Products", tableName: "Localizable", source: source, developmentValue: "Popular Products", comment: nil) }

      /// en translation: Popular Search
      ///
      /// Key: Popular Search
      ///
      /// Locales: en
      var popularSearch: RswiftResources.StringResource { .init(key: "Popular Search", tableName: "Localizable", source: source, developmentValue: "Popular Search", comment: nil) }

      /// en translation: Price
      ///
      /// Key: Price
      ///
      /// Locales: en
      var price: RswiftResources.StringResource { .init(key: "Price", tableName: "Localizable", source: source, developmentValue: "Price", comment: nil) }

      /// en translation: Rating
      ///
      /// Key: Rating
      ///
      /// Locales: en
      var rating: RswiftResources.StringResource { .init(key: "Rating", tableName: "Localizable", source: source, developmentValue: "Rating", comment: nil) }

      /// en translation: Register Success
      ///
      /// Key: Register Success
      ///
      /// Locales: en
      var registerSuccess: RswiftResources.StringResource { .init(key: "Register Success", tableName: "Localizable", source: source, developmentValue: "Register Success", comment: nil) }

      /// en translation: Resend
      ///
      /// Key: Resend
      ///
      /// Locales: en
      var resend: RswiftResources.StringResource { .init(key: "Resend", tableName: "Localizable", source: source, developmentValue: "Resend", comment: nil) }

      /// en translation: Search
      ///
      /// Key: Search
      ///
      /// Locales: en
      var search: RswiftResources.StringResource { .init(key: "Search", tableName: "Localizable", source: source, developmentValue: "Search", comment: nil) }

      /// en translation: Search something...
      ///
      /// Key: Search Something
      ///
      /// Locales: en
      var searchSomething: RswiftResources.StringResource { .init(key: "Search Something", tableName: "Localizable", source: source, developmentValue: "Search something...", comment: nil) }

      /// en translation: See All
      ///
      /// Key: See All
      ///
      /// Locales: en
      var seeAll: RswiftResources.StringResource { .init(key: "See All", tableName: "Localizable", source: source, developmentValue: "See All", comment: nil) }

      /// en translation: Select location
      ///
      /// Key: Select location
      ///
      /// Locales: en
      var selectLocation: RswiftResources.StringResource { .init(key: "Select location", tableName: "Localizable", source: source, developmentValue: "Select location", comment: nil) }

      /// en translation: Send code
      ///
      /// Key: Send code
      ///
      /// Locales: en
      var sendCode: RswiftResources.StringResource { .init(key: "Send code", tableName: "Localizable", source: source, developmentValue: "Send code", comment: nil) }

      /// en translation: Shipping:
      ///
      /// Key: Shipping:
      ///
      /// Locales: en
      var shipping: RswiftResources.StringResource { .init(key: "Shipping:", tableName: "Localizable", source: source, developmentValue: "Shipping:", comment: nil) }

      /// en translation: Sign In
      ///
      /// Key: Sign In
      ///
      /// Locales: en
      var signIn: RswiftResources.StringResource { .init(key: "Sign In", tableName: "Localizable", source: source, developmentValue: "Sign In", comment: nil) }

      /// en translation: Sign In with Facebook
      ///
      /// Key: Sign In with Facebook
      ///
      /// Locales: en
      var signInWithFacebook: RswiftResources.StringResource { .init(key: "Sign In with Facebook", tableName: "Localizable", source: source, developmentValue: "Sign In with Facebook", comment: nil) }

      /// en translation: Sign In with Google
      ///
      /// Key: Sign In with Google
      ///
      /// Locales: en
      var signInWithGoogle: RswiftResources.StringResource { .init(key: "Sign In with Google", tableName: "Localizable", source: source, developmentValue: "Sign In with Google", comment: nil) }

      /// en translation: Snap buy
      ///
      /// Key: Snap buy
      ///
      /// Locales: en
      var snapBuy: RswiftResources.StringResource { .init(key: "Snap buy", tableName: "Localizable", source: source, developmentValue: "Snap buy", comment: nil) }

      /// en translation: Start shopping with registered account
      ///
      /// Key: Start shopping with registered account
      ///
      /// Locales: en
      var startShoppingWithRegisteredAccount: RswiftResources.StringResource { .init(key: "Start shopping with registered account", tableName: "Localizable", source: source, developmentValue: "Start shopping with registered account", comment: nil) }

      /// en translation: Store
      ///
      /// Key: Store
      ///
      /// Locales: en
      var store: RswiftResources.StringResource { .init(key: "Store", tableName: "Localizable", source: source, developmentValue: "Store", comment: nil) }

      /// en translation: %@ Products  •  %@ Followers
      ///
      /// Key: StoreStatsFormat
      ///
      /// Locales: en
      var storeStatsFormat: RswiftResources.StringResource2<String, String> { .init(key: "StoreStatsFormat", tableName: "Localizable", source: source, developmentValue: "%@ Products  •  %@ Followers", comment: nil) }

      /// en translation: Submit
      ///
      /// Key: Submit
      ///
      /// Locales: en
      var submit: RswiftResources.StringResource { .init(key: "Submit", tableName: "Localizable", source: source, developmentValue: "Submit", comment: nil) }

      /// en translation: Subtotal:
      ///
      /// Key: Subtotal:
      ///
      /// Locales: en
      var subtotal: RswiftResources.StringResource { .init(key: "Subtotal:", tableName: "Localizable", source: source, developmentValue: "Subtotal:", comment: nil) }

      /// en translation: Your order will be packed by the clerk, will arrive at your hour in 3 to 4 days
      ///
      /// Key: Successful Order 
      ///
      /// Locales: en
      var successfulOrder: RswiftResources.StringResource { .init(key: "Successful Order ", tableName: "Localizable", source: source, developmentValue: "Your order will be packed by the clerk, will arrive at your hour in 3 to 4 days", comment: nil) }

      /// en translation: Total amount:
      ///
      /// Key: Total amount:
      ///
      /// Locales: en
      var totalAmount: RswiftResources.StringResource { .init(key: "Total amount:", tableName: "Localizable", source: source, developmentValue: "Total amount:", comment: nil) }

      /// en translation: Upbox Bag
      ///
      /// Key: Upbox Bag
      ///
      /// Locales: en
      var upboxBag: RswiftResources.StringResource { .init(key: "Upbox Bag", tableName: "Localizable", source: source, developmentValue: "Upbox Bag", comment: nil) }

      /// en translation: Username
      ///
      /// Key: Username
      ///
      /// Locales: en
      var username: RswiftResources.StringResource { .init(key: "Username", tableName: "Localizable", source: source, developmentValue: "Username", comment: nil) }

      /// en translation: Verification Code
      ///
      /// Key: Verification Code
      ///
      /// Locales: en
      var verificationCode: RswiftResources.StringResource { .init(key: "Verification Code", tableName: "Localizable", source: source, developmentValue: "Verification Code", comment: nil) }

      /// en translation: We have sent the code verification to %@
      ///
      /// Key: We have sent the code verification to
      ///
      /// Locales: en
      var weHaveSentTheCodeVerificationTo: RswiftResources.StringResource1<String> { .init(key: "We have sent the code verification to", tableName: "Localizable", source: source, developmentValue: "We have sent the code verification to %@", comment: nil) }

      /// en translation: Your account will be created as soon as you filled all the information needed!
      ///
      /// Key: Your account will be created as soon as you filled all the information needed
      ///
      /// Locales: en
      var yourAccountWillBeCreatedAsSoonAsYouFilledAllTheInformationNeeded: RswiftResources.StringResource { .init(key: "Your account will be created as soon as you filled all the information needed", tableName: "Localizable", source: source, developmentValue: "Your account will be created as soon as you filled all the information needed!", comment: nil) }

      /// en translation: Products (%d)
      ///
      /// Key: countProductFormat
      ///
      /// Locales: en
      var countProductFormat: RswiftResources.StringResource1<Int> { .init(key: "countProductFormat", tableName: "Localizable", source: source, developmentValue: "Products (%d)", comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 2 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `BgColor`.
    var bgColor: RswiftResources.ColorResource { .init(name: "BgColor", path: [], bundle: bundle) }

    /// Color `MainColor`.
    var mainColor: RswiftResources.ColorResource { .init(name: "MainColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 37 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `Up_1`.
    var up_1: RswiftResources.ImageResource { .init(name: "Up_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cat_access`.
    var cat_access: RswiftResources.ImageResource { .init(name: "cat_access", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cat_bags`.
    var cat_bags: RswiftResources.ImageResource { .init(name: "cat_bags", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cat_clothes`.
    var cat_clothes: RswiftResources.ImageResource { .init(name: "cat_clothes", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cat_new`.
    var cat_new: RswiftResources.ImageResource { .init(name: "cat_new", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cat_shoes`.
    var cat_shoes: RswiftResources.ImageResource { .init(name: "cat_shoes", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_1`.
    var img_1: RswiftResources.ImageResource { .init(name: "img_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_2`.
    var img_2: RswiftResources.ImageResource { .init(name: "img_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_3`.
    var img_3: RswiftResources.ImageResource { .init(name: "img_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_COD`.
    var img_COD: RswiftResources.ImageResource { .init(name: "img_COD", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_a`.
    var img_a: RswiftResources.ImageResource { .init(name: "img_a", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_ccard`.
    var img_ccard: RswiftResources.ImageResource { .init(name: "img_ccard", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_email`.
    var img_email: RswiftResources.ImageResource { .init(name: "img_email", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_email_verification`.
    var img_email_verification: RswiftResources.ImageResource { .init(name: "img_email_verification", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_facebook_icon`.
    var img_facebook_icon: RswiftResources.ImageResource { .init(name: "img_facebook_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_google_icon`.
    var img_google_icon: RswiftResources.ImageResource { .init(name: "img_google_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_hide_pw`.
    var img_hide_pw: RswiftResources.ImageResource { .init(name: "img_hide_pw", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_ob1`.
    var img_ob1: RswiftResources.ImageResource { .init(name: "img_ob1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_ob2`.
    var img_ob2: RswiftResources.ImageResource { .init(name: "img_ob2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_ob3`.
    var img_ob3: RswiftResources.ImageResource { .init(name: "img_ob3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_password`.
    var img_password: RswiftResources.ImageResource { .init(name: "img_password", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_paypal`.
    var img_paypal: RswiftResources.ImageResource { .init(name: "img_paypal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_show_pw`.
    var img_show_pw: RswiftResources.ImageResource { .init(name: "img_show_pw", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_success_check`.
    var img_success_check: RswiftResources.ImageResource { .init(name: "img_success_check", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_successfulorder`.
    var img_successfulorder: RswiftResources.ImageResource { .init(name: "img_successfulorder", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_user`.
    var img_user: RswiftResources.ImageResource { .init(name: "img_user", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `imgb_1`.
    var imgb_1: RswiftResources.ImageResource { .init(name: "imgb_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `imgb_2`.
    var imgb_2: RswiftResources.ImageResource { .init(name: "imgb_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `imgb_3`.
    var imgb_3: RswiftResources.ImageResource { .init(name: "imgb_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `up_2`.
    var up_2: RswiftResources.ImageResource { .init(name: "up_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `up_3`.
    var up_3: RswiftResources.ImageResource { .init(name: "up_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ver_1`.
    var ver_1: RswiftResources.ImageResource { .init(name: "ver_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ver_2`.
    var ver_2: RswiftResources.ImageResource { .init(name: "ver_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ver_3`.
    var ver_3: RswiftResources.ImageResource { .init(name: "ver_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ver_4`.
    var ver_4: RswiftResources.ImageResource { .init(name: "ver_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ver_5`.
    var ver_5: RswiftResources.ImageResource { .init(name: "ver_5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ver_6`.
    var ver_6: RswiftResources.ImageResource { .init(name: "ver_6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.font` struct is generated, and contains static references to 12 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `Inter-Bold`.
    var interBold: RswiftResources.FontResource { .init(name: "Inter-Bold", bundle: bundle, filename: "Inter-Bold.ttf") }

    /// Font `Inter-Regular`.
    var interRegular: RswiftResources.FontResource { .init(name: "Inter-Regular", bundle: bundle, filename: "Inter-Regular.ttf") }

    /// Font `Inter-SemiBold`.
    var interSemiBold: RswiftResources.FontResource { .init(name: "Inter-SemiBold", bundle: bundle, filename: "Inter-SemiBold.ttf") }

    /// Font `Outfit-Black`.
    var outfitBlack: RswiftResources.FontResource { .init(name: "Outfit-Black", bundle: bundle, filename: "Outfit-Black.ttf") }

    /// Font `Outfit-Bold`.
    var outfitBold: RswiftResources.FontResource { .init(name: "Outfit-Bold", bundle: bundle, filename: "Outfit-Bold.ttf") }

    /// Font `Outfit-ExtraBold`.
    var outfitExtraBold: RswiftResources.FontResource { .init(name: "Outfit-ExtraBold", bundle: bundle, filename: "Outfit-ExtraBold.ttf") }

    /// Font `Outfit-ExtraLight`.
    var outfitExtraLight: RswiftResources.FontResource { .init(name: "Outfit-ExtraLight", bundle: bundle, filename: "Outfit-ExtraLight.ttf") }

    /// Font `Outfit-Light`.
    var outfitLight: RswiftResources.FontResource { .init(name: "Outfit-Light", bundle: bundle, filename: "Outfit-Light.ttf") }

    /// Font `Outfit-Medium`.
    var outfitMedium: RswiftResources.FontResource { .init(name: "Outfit-Medium", bundle: bundle, filename: "Outfit-Medium.ttf") }

    /// Font `Outfit-Regular`.
    var outfitRegular: RswiftResources.FontResource { .init(name: "Outfit-Regular", bundle: bundle, filename: "Outfit-Regular.ttf") }

    /// Font `Outfit-SemiBold`.
    var outfitSemiBold: RswiftResources.FontResource { .init(name: "Outfit-SemiBold", bundle: bundle, filename: "Outfit-SemiBold.ttf") }

    /// Font `Outfit-Thin`.
    var outfitThin: RswiftResources.FontResource { .init(name: "Outfit-Thin", bundle: bundle, filename: "Outfit-Thin.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [interBold, interRegular, interSemiBold, outfitBlack, outfitBold, outfitExtraBold, outfitExtraLight, outfitLight, outfitMedium, outfitRegular, outfitSemiBold, outfitThin].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 13 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Inter-Bold.ttf`.
    var interBoldTtf: RswiftResources.FileResource { .init(name: "Inter-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Regular.ttf`.
    var interRegularTtf: RswiftResources.FileResource { .init(name: "Inter-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-SemiBold.ttf`.
    var interSemiBoldTtf: RswiftResources.FileResource { .init(name: "Inter-SemiBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Outfit-Black.ttf`.
    var outfitBlackTtf: RswiftResources.FileResource { .init(name: "Outfit-Black", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Outfit-Bold.ttf`.
    var outfitBoldTtf: RswiftResources.FileResource { .init(name: "Outfit-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Outfit-ExtraBold.ttf`.
    var outfitExtraBoldTtf: RswiftResources.FileResource { .init(name: "Outfit-ExtraBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Outfit-ExtraLight.ttf`.
    var outfitExtraLightTtf: RswiftResources.FileResource { .init(name: "Outfit-ExtraLight", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Outfit-Light.ttf`.
    var outfitLightTtf: RswiftResources.FileResource { .init(name: "Outfit-Light", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Outfit-Medium.ttf`.
    var outfitMediumTtf: RswiftResources.FileResource { .init(name: "Outfit-Medium", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Outfit-Regular.ttf`.
    var outfitRegularTtf: RswiftResources.FileResource { .init(name: "Outfit-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Outfit-SemiBold.ttf`.
    var outfitSemiBoldTtf: RswiftResources.FileResource { .init(name: "Outfit-SemiBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Outfit-Thin.ttf`.
    var outfitThinTtf: RswiftResources.FileResource { .init(name: "Outfit-Thin", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `credentials.plist`.
    var credentialsPlist: RswiftResources.FileResource { .init(name: "credentials", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }
  }
}